# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget peloton peloton-proto)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target peloton
add_library(peloton SHARED IMPORTED)

# Create imported target peloton-proto
add_library(peloton-proto STATIC IMPORTED)

# Import target "peloton" for configuration "Release"
set_property(TARGET peloton APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(peloton PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "peloton-proto;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_atomic.so;/usr/lib/x86_64-linux-gnu/libpthread.so;-lpthread;/usr/lib/x86_64-linux-gnu/libgflags.so;/usr/local/lib/libprotobuf.so;-lpthread;/usr/lib/x86_64-linux-gnu/libevent.so;/usr/lib/x86_64-linux-gnu/libpqxx.so;/usr/lib/x86_64-linux-gnu/libpq.so;peloton-proto;/home/zq/15721-peloton/15721-peloton-hey-pull-from-here/third_party/libpg_query/libpg_query.a"
  IMPORTED_LOCATION_RELEASE "/home/zq/15721-peloton/15721-peloton-hey-pull-from-here/tpcc_build/lib/libpeloton.so.0.0.5"
  IMPORTED_SONAME_RELEASE "libpeloton.so.0.0.5"
  )

# Import target "peloton-proto" for configuration "Release"
set_property(TARGET peloton-proto APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(peloton-proto PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/zq/15721-peloton/15721-peloton-hey-pull-from-here/tpcc_build/lib/libpeloton-proto.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
